
webmagic:
  site:
    sehuatang:
      name: SeHuaTang
      host: https://xzcfdfsafd.co
      thread-size: 4
      extras:
        torrent-file-save-path: C:/Users/nekoimi/Downloads/tmp/torrent-file